name: Terraform Apply (Sandbox)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Terraform Init (remote state)
        working-directory: infra/env/sandbox
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_BACKEND_BUCKET }}" \
            -backend-config="key=sandbox/terraform.tfstate" \
            -backend-config="region=us-east-2" \
            -backend-config="dynamodb_table=${{ vars.TF_BACKEND_DDB_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Apply
        working-directory: infra/env/sandbox
        env:
          TF_VAR_enable_github_actions_oidc: "true"
          TF_VAR_enable_budgets: "true"
          TF_VAR_budget_notification_emails: ${{ vars.BUDGET_NOTIFICATION_EMAILS }}
          TF_VAR_enable_budget_notifications: ${{ vars.BUDGET_NOTIFICATION_EMAILS != '' && 'true' || 'false' }}
        run: terraform apply -auto-approve
